### ISSUE TITLE
Prompting for supervised student-centered learning

### ISSUE THREAD

**Issue by xabier** [juananpe/gen-ai-in-softeng#2]
More than contributing with a specifi prompt (I have one suggestion as an example bellow) I wanted to contribute to this project with a note on how I think it might be more fruitful to make prompts for students. I have been looking to some of the prompts you have systematized (nice job!) and I think chatGPT (or other LLMs) can be pushed a bit futher for teaching. 

Instead of prompting the LLM with a specific question, I find more powerfull to prompt the LLM with some teaching instructions so that the LLM guides the student in a personalized manner as a coach. 

Here is an example:

PROMPT:
```
You are a computer science lecturer that handles students nicely but in a direct and helpfull maner, correcting their mistakes, and indicating ways to improve their learning. You should help the student step by step. Waiting for the students response in each step. Do not give him/her all the instructions at once. Be patient and test whether the student has understood each exercise.

Show the student how to use git in five steps, increasing the level of difficulty in each step. You should suggest small practical exercises to the student. Start with what the student has to install on a linux terminal and then start with the first steps to lear git.
```

Here is a screen capture of how the prompt works with a student that made a mistake in the first step:

![image](https://github.com/juananpe/gen-ai-in-softeng/assets/537284/bccd0892-d0b7-427e-9346-0a58e0389ed2)

thank you very much for this repo, I find this kind of projects very helpfull, I might not be able to help any further with software engineering teaching since I teach in the Philosophy department, but I hope my suggestion helps :smile: 

thanks @mikel-egana-aranguren for pointing out this project to me

**Comment by xabier** [comment]
I also forgot to mention that the testing of this kind of prompts add more value to he project because, for instance I don't know if 5 steps are sufficient to learn git basics starting with installing it, would 10 be more adecuate? 8? All these has to be tested and it also depends on the approach that GPT takes on selecting the steps.

And congratulations again for the site, I keep disconvering interesting prompts!

**Comment by juananpe** [comment]
Wow! Thank you, Xabier, for your feedback and contribution. I love your prompt suggestion! We will definitely add it, but now we need to create a new Knowledge Area (KA) - aka folder - for it in the repo, because your prompt is not linked to a single KA (it covers a lot of them!). That's not a problem but I'd like to think about it and discuss it with my colleagues (hopefully today) to do it right. Thanks again! I'll keep you posted.

**Comment by juananpe** [comment]
Added as https://github.com/juananpe/gen-ai-in-softeng/tree/main/Supervised%20Learning
Let me know if you would like to see it in another category/folder

**Comment by xabier** [comment]
Sorry for the late response. I don't often get back to github. Thanks @juananpe for the new category and for the project!
